import { type Topic, type Difficulty } from "./types";

export const RSS_FEEDS = [
  {
    name: "The Hindu - National",
    url: "https://www.thehindu.com/news/national/feeder/default.rss",
    category: "general",
  },
  {
    name: "The Hindu - Business",
    url: "https://www.thehindu.com/business/feeder/default.rss",
    category: "economy",
  },
  {
    name: "The Hindu - Science",
    url: "https://www.thehindu.com/sci-tech/science/feeder/default.rss",
    category: "science",
  },
  {
    name: "Indian Express - India",
    url: "https://indianexpress.com/section/india/feed/",
    category: "general",
  },
  {
    name: "Indian Express - Economy",
    url: "https://indianexpress.com/section/business/economy/feed/",
    category: "economy",
  },
  {
    name: "PIB - Press Releases",
    url: "https://pib.gov.in/RssMain.aspx?ModId=6&Lang=1&Regid=3",
    category: "government",
  },
  {
    name: "LiveMint - Economy",
    url: "https://www.livemint.com/rss/economy",
    category: "economy",
  },
  {
    name: "Down To Earth - Environment",
    url: "https://www.downtoearth.org.in/rss/news",
    category: "environment",
  },
];

export const TOPIC_KEYWORDS: Record<Topic, string[]> = {
  polity: [
    "parliament",
    "supreme court",
    "constitution",
    "bill",
    "amendment",
    "governor",
    "election",
    "fundamental rights",
    "judiciary",
    "lok sabha",
    "rajya sabha",
    "cabinet",
    "high court",
    "article",
    "speaker",
    "president",
    "legislative",
    "panchayat",
    "municipal",
    "eci",
    "election commission",
    "cag",
    "upsc",
    "tribunal",
    "lokpal",
  ],
  economy: [
    "gdp",
    "rbi",
    "inflation",
    "fiscal",
    "budget",
    "trade",
    "export",
    "import",
    "monetary",
    "bank",
    "tax",
    "gst",
    "investment",
    "niti aayog",
    "disinvestment",
    "rupee",
    "sebi",
    "stock",
    "pli",
    "msme",
    "fdi",
    "current account",
    "subsidy",
    "fintech",
    "upi",
  ],
  environment: [
    "climate",
    "biodiversity",
    "wildlife",
    "forest",
    "pollution",
    "carbon",
    "renewable",
    "conservation",
    "species",
    "wetland",
    "coral",
    "emission",
    "national park",
    "tiger",
    "mangrove",
    "waste",
    "ozone",
    "cop",
    "paris agreement",
    "green hydrogen",
    "solar",
    "wind energy",
    "ev",
    "ethanol",
  ],
  history_culture: [
    "heritage",
    "culture",
    "archaeological",
    "festival",
    "temple",
    "unesco",
    "monument",
    "ancient",
    "civilization",
    "classical",
    "tribal",
    "art form",
    "dance",
    "music",
    "literature",
    "mughal",
    "chola",
    "gupta",
    "indus",
    "vedic",
    "freedom movement",
    "gandhi",
    "nehru",
  ],
  current_affairs: [
    "isro",
    "space",
    "defense",
    "military",
    "technology",
    "digital",
    "cyber",
    "bilateral",
    "summit",
    "un",
    "who",
    "g20",
    "brics",
    "diplomacy",
    "missile",
    "satellite",
    "ai",
    "semiconductor",
    "quantum",
    "nuclear",
    "nato",
    "asean",
    "quad",
  ],
};

export const TOPIC_DISTRIBUTION: Record<Topic, number> = {
  polity: 2,
  economy: 2,
  environment: 2,
  history_culture: 2,
  current_affairs: 2,
};

export const DIFFICULTY_DISTRIBUTION: Record<Difficulty, number> = {
  easy: 3,
  medium: 5,
  hard: 2,
};

export const CACHE_TTL: Record<string, number> = {
  last_week: 24 * 60 * 60 * 1000,
  last_month: 3 * 24 * 60 * 60 * 1000,
  last_year: 7 * 24 * 60 * 60 * 1000,
};
